
## Question 1


```{r}
#a
sal <- read.table("salamanders.txt")
sal
View(sal)

#b
# structures
str(sal)


# number of rows
nrow(sal)

# number of columns/variables
ncol(sal)

# c
colnames(sal) <- sal[1, ]

sal <- sal[-1, ]


View(sal)
```


## Question 3

```{r}
# a

std_dev <- sd(sal$CWD)

std_dev

avg <- mean(as.numeric(sal$CWD))
avg

cv <- std_dev/avg *100

cv

# b

iqr <- IQR(sal$CWD)

```

# Question 4

```{r}
# a
# ecdf graph
plot(ecdf(as.numeric(sal$CWD)), 
     main = "ECDF of CWD",
     xlab = "CWD",
     ylab = "F(x)")


# b
# histogram
hist(as.numeric(sal$CWD),
     main = "Histogram of CWD",
     xlab = "CWD",
     col = "red")

# c
plot(density(as.numeric(sal$CWD)),
     main = "Kernel Denssity of CWD",
     xlab = " CWD")

# d
boxplot(as.numeric(sal$CWD),
        main = "Boxplot of CWD",
        ylab = "CWD")

```


## Question 5

```{r}

stat_vars <- sal[, c("abund", "fecund", "CWD")]

View(stat_vars)

stat_vars$abund <- as.numeric(stat_vars$abund)

stat_vars$fecund <- as.numeric(stat_vars$fecund)

stat_vars$CWD <- as.numeric(stat_vars$CWD)


# a
# covariance matrix
cov(stat_vars)

# b
# pearson's correlation matrix
cor(stat_vars, method = "pearson")

# c
# spearman correlation matrix
cor(stat_vars, method = "spearman")

```

# Question 6

```{r}
hist(as.numeric(sal$CWD))

shapiro.test(as.numeric(sal$CWD))

hist(log(as.numeric(sal$CWD)))

hist(sqrt(as.numeric(sal$CWD)))

shapiro.test(log(as.numeric(sal$CWD)))


shapiro.test(sqrt(as.numeric(sal$CWD)))
```


## Question 7
```{r}

sal_scaled <- scale(stat_vars)

sal_scaled

colMeans(sal_scaled)
```


# No, because the rows represent different observations
# and not different variables. If it were to represent
# different variables, then one can use row standardization





