

## Efficiency

### Question 1
```{r}

set.seed(43)

rbeta(40, shape1 = 2, shape2 = 0.7)

samples <- replicate(1000, rbeta(40, shape1 = 2, shape2 = 0.7))
```



### Question 2

```{r}
add <- function(a, b){
  print(a + b)
}

add(2, 2)

## installing
#install.packages("fitdistrplus")

## load package
library(fitdistrplus)

estbeta.ml<-function(y)
{
  coefficients(fitdist(y,distr="beta"))
}

ml_estimates <- apply(samples, 2, estbeta.ml)

ml_estimates <- t(apply(samples, 2, estbeta.ml))

par(mfrow = c(1,2))

hist(ml_estimates[,1], prob = TRUE)

lines(density(ml_estimates[,1]))

hist(ml_estimates[,2], prob = TRUE)

lines(density(ml_estimates[,2]))
```


### Question 4

```{r}

# alpha
sd(ml_estimates[,1])

# beta
sd(ml_estimates[,2])
```


## Question 5

```{r}
estbeta.mm <- function(y){
  m <- mean(y)
  v <- var(y)
  alpha_mm <- m * ((m * (1 - m)/v)-1)
  beta_mm <- (1 - m)*(((m * (1 - m))/v)-1)
  c(shape1 = alpha_mm, shape2 = beta_mm)
}

mm_estimates <- apply(samples, 2, estbeta.mm)

mm_estimates <- t(apply(samples, 2, estbeta.mm))


se_mm_alpha <- sd(mm_estimates[,1])
se_mm_beta <- sd(mm_estimates[,2])

se_mm_alpha
se_mm_beta
```


## The TcCB Data

### Question 1

```{r}
EPA.94b.tccb.df <- read.csv("EPA.94b.tccb.df.txt")
```

### Question 2

```{r}
cleanup <- subset(EPA.94b.tccb.df, Area == "Cleanup")

cleanup <- cleanup$TcCB
```


### Question 3

```{r}
bc <- boxcox(cleanup ~ 1, lambda = seq(-2,2,by = 0.01))

which.max(bc$y)

lambda_opt <- bc$x[which.max(bc$y)]

cleanup_transformed <- (cleanup^lambda_opt - 1)/lambda_opt


# plot a density for the above histogram
plot(density(cleanup_transformed), 
     col = "blue", 
     main = "Density of Transformed Cleanup Data")

plot(density(cleanup), 
     col = "blue", 
     main = "Density of Transformed Cleanup Data")
```


### Question 4

```{r}

library(fitdistrplus)

fit <- fitdist(cleanup_transformed, "norm")
fit

mean_estimate <- -0.9499
sd_estimate <- 1.3837
```


### Question 5

```{r}

q99_transformed <- qnorm(0.99, 
                         mean = mean_estimate,
                         sd = sd_estimate)
q99_transformed
```


### Question 6

```{r}
a <- exp(q99_transformed)
a
```


### Question 7

```{r}
p = 0.01

pbinom(0, size = 3, prob = 0.01, lower.tail = FALSE)
```


## Tropical Cyclones

```{r}
us <- read.table("US.txt")

colnames(us) <- us[1,]
us <- us[-1,]
```

### question 1

```{r}
hurricanes <- as.numeric(us$US)

hist(hurricanes, prob = TRUE)

# poisson distribution is used for rare events and also
# count data
```

### question 2

```{r}
lambda <- mean(hurricanes)
lambda

## lamba is the mean and also the variance of poisson
## distribution
```


## Whales

```{r}
whales <- read.table("whales.txt")

whales <- as.numeric(whales$V1)
```


### Question 1

```{r}
hist(whales)
```


### Question 2

Yes a gamma distribution is plausible because swimming can't be negative.


### Question 3

```{r}
mean_bar <- mean(whales)
s2 <- var(whales)

alpha_mom <- mean_bar^2/s2
beta_mom <- mean_bar/s2
alpha_mom
beta_mom
```


### Question 4

```{r}
## maximum likelihood

fit_gamma_ml <- fitdist(whales, "gamma")
fit_gamma_ml

alpha_ml <- 1.595511
beta_ml <- 2.632771

## The values are not the same but different
```


### Question 5

```{r}

hist(whales, prob = TRUE)

x <- seq(0, max(whales),length.out = 500)

lines(x, dgamma(x, alpha_mom, rate = beta_mom),
      col = "blue")

lines(x, dgamma(x, alpha_ml, rate = beta_ml),
      col = "red")

```

