---
title: "h2"
format: html
---
## Question 1

```{r}
x <- 3
y <- 4
# a
a1 <- log(x + y) * x * y
a1

# b
a2 <- log10((x*y)/2)
a2

# c
a3 <- (2 * x^(1/3)) + (y^(1/4))
a3

# d
a4 <- (10^(x-y)) + exp(x*y)
a4
```


## Question 2

```{r}
x <- c(4, 6, 5, 7, 10, 9, 4, 15)

# a
b1 <- x < 7
b1

# b
b2 <- x == 7
b2

# c
x = 7

b3 <- x
b3

# <=
# >= 
# !=

# d
x <- c(4, 6, 5, 7, 10, 9, 4, 15)

mean(x)

a <- sum(x)
a

b <- length(x)
b

a/b

avg <- sum(x)/length(x)
avg

# d

sub_vector <- x[x > avg]

# e
max_subvector <- max(sub_vector)
max_subvector
```



## Question 3

```{r}
# a
A <- matrix(c(1, 3, 2, 5, 4, 3, 4, 4), nrow = 2, ncol = 4)
A

colnames(A) <- c("Col1", "Col2", "Col3", "Col4")
A

# b
B = A + 3
B

# c
A + B

# d
D <- cbind(A, c(1,2))
D

# e
D[ , 3]


```


## Question 4

```{r}
# a
LETTERS[18]

#b 
LETTERS[length(LETTERS)]

#c 
Names <- c("John", "Andrew", "Thomas")
Designation <- c("Manager", "Project Head", "Marketing Head")

cbind(Names, Designation)

cbind(c("John", "Andrew", "Thomas"), 
      c("Manager", "Project Head", "Marketing Head"))

# d
friend <- c("Peter", "John")
city <- c("Abuja", "Warri")

paste(friend,"lives in", city)

#e


```





# Question 5

```{r}
#a

names <- c("Bob", "Alice", "Jane")
age <- c(22, 65, 36)
flag <- c(FALSE, FALSE, TRUE)

df <- data.frame(names, age, flag)
df

# b
df$score <- c(50, 60, 90)

df

# c

## add a row
new_name = "Tom"
new_age = 43
new_flag = FALSE
new_score = 67

new_row <- data.frame(names = new_name, 
                      age = new_age,
                      flag = new_flag,
                      score = new_score)

new_row <- data.frame(names = "Tom", 
                      age = 43,
                      flag = FALSE,
                      score = 67)

new_row

new_df <- rbind(df, new_row)
new_df

```

## Question 6

```{r}
# a
View(airquality)


airquality$Date_character <- paste(airquality$Day,
                         airquality$Month,
                         "1973",
                         sep = "-")

airquality$Date <- as.Date(paste(airquality$Day,
                                 airquality$Month,
                                 "1973",
                                 sep = "-"),
                           "%d-%m-%Y")

View(airquality)

# b

names(airquality)[4] <- "Temperature"
names(airquality)[2] <- "Solar Radiation"

names(airquality)[names(airquality) == "Ozone"] <- "ozone"

Temperature <- (airquality$Temperature - 32)/1.8
```


## Question 7

```{r}
# a 
hot <- max(airquality$Temperature)
cold <- min(airquality$Temperature)
hot
cold

which.max(airquality$Temperature)

which.min(airquality$Temperature)

airquality$Date[which.max(airquality$Temperature)]

airquality$Date[which.min(airquality$Temperature)]

airquality$ozone[which.max(airquality$Temperature)]

airquality$Date[which.max(airquality$Wind)]

# b
mean(airquality$Wind)

airquality$Wind > mean(airquality$Wind)

sum(airquality$Wind > mean(airquality$Wind))

#c
complete.cases(airquality)

sum(complete.cases(airquality))

#d
airquality$Date[airquality$`Solar Radiation` > 300]

airquality$Date[!is.na(airquality$`Solar Radiation`) &
  airquality$`Solar Radiation` > 300]
```



# Question 9
```{r}
climate <- read.csv("ncdc_galesburg_daily_climate.csv")

View(climate)

climate[climate == -9999] <- NA

climate$DATE <- as.Date(as.character(climate$DATE), 
                        format = 
                          "%Y%m%d")
```









